### ISSUE TITLE
Problems with Blade UI Kit icons 

### ISSUE THREAD

**Issue by Pennywise96** [assertchris/laravel-renderless-components#1]
Hey,
first of all, really awesome package!

There is a issue when I'm using your package + the Blade UI Kit icons.
After installing your package all icons lose their classes ($attributes).

Do you have also this problem?

**Comment by assertchris** [comment]
Oh, I haven't tried with that yet. Thanks for reporting; will check it out...

**Comment by Pennywise96** [comment]
@assertchris Thank you!
Also when I'm install your package and run the command ``` composer dump-autoload ```, I get the error ``` syntax error, unexpected 'endif' (T_ENDIF), expecting end of file ``` on a random blade component.

**Comment by assertchris** [comment]
Apologies for not getting back to you about this sooner. This repo is basically abandonware, at this point. Feel free to fork it (or take it over if you like, I can transfer).
